/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CourseRouteImport } from './routes/course'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonModuleIdLessonIdRouteImport } from './routes/lesson.$moduleId.$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonModuleIdLessonIdRoute = LessonModuleIdLessonIdRouteImport.update({
  id: '/lesson/$moduleId/$lessonId',
  path: '/lesson/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/login': typeof LoginRoute
  '/lesson/$moduleId/$lessonId': typeof LessonModuleIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/login': typeof LoginRoute
  '/lesson/$moduleId/$lessonId': typeof LessonModuleIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/course': typeof CourseRoute
  '/login': typeof LoginRoute
  '/lesson/$moduleId/$lessonId': typeof LessonModuleIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/course' | '/login' | '/lesson/$moduleId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/course' | '/login' | '/lesson/$moduleId/$lessonId'
  id: '__root__' | '/' | '/course' | '/login' | '/lesson/$moduleId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseRoute: typeof CourseRoute
  LoginRoute: typeof LoginRoute
  LessonModuleIdLessonIdRoute: typeof LessonModuleIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$moduleId/$lessonId': {
      id: '/lesson/$moduleId/$lessonId'
      path: '/lesson/$moduleId/$lessonId'
      fullPath: '/lesson/$moduleId/$lessonId'
      preLoaderRoute: typeof LessonModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseRoute: CourseRoute,
  LoginRoute: LoginRoute,
  LessonModuleIdLessonIdRoute: LessonModuleIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
